### ISSUE TITLE
Search bar for food

### ISSUE THREAD

**Issue by AkhilS2** [HungrySlugs-CSE115A/hungry-slugs-webapp#35]

**Comment by IanHollow** [comment]
@tiwariakshat47
* this task is not done the tasks was:
  * Implement a search bar on the food page for each dining hall that filters food that matches the search query. (3 hr) [Search all dining halls for a specific food. There will be some sort of searching page]
* you have done the first part but there also needs to be a search page with search mechanism across all the dining halls

**Comment by tiwariakshat47** [comment]
Search mechanism through all the pages is finished, but we have discussed and it was finalized that we needed to make the search menu also cause everything else on the page to disappear, which I will continue to try and fix.
