### ISSUE TITLE
Filter by time

### ISSUE THREAD

**Issue by AkhilS2** [HungrySlugs-CSE115A/hungry-slugs-webapp#39]

**Comment by tiwariakshat47** [comment]
Created accordian menu; UI not 100% fixed

**Comment by IanHollow** [comment]
@tiwariakshat47 
* this task is not done
* the task was: Check the time of day to hide and show certain meals to users.
* I noticed that you implemented the accordion menu to show or not show a option on the menu. However, it is not connected to the time of day.
